// p3/fitnessrecord/src/components/layout/BottomNav.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { Home, Dumbbell, Calendar, BarChart3, Settings } from 'lucide-vue-next';

const route = useRoute();
const router = useRouter();

const navItems = [
  { path: '/', icon: Home, label: '首页' },
  { path: '/exercises', icon: Dumbbell, label: '动作' },
  { path: '/plans', icon: Calendar, label: '计划' },
  { path: '/stats', icon: BarChart3, label: '统计' },
  { path: '/settings', icon: Settings, label: '设置' }
];

const isActive = (path: string) => computed(() => route.path === path);

const navigate = (path: string) => {
  router.push(path);
};
</script>

<template>
  <nav class="fixed bottom-0 left-0 right-0 bg-gray-900/95 backdrop-blur-lg border-t border-gray-800 safe-area-bottom z-40">
    <div class="flex justify-around items-center h-16 max-w-lg mx-auto px-2">
      <button
        v-for="item in navItems"
        :key="item.path"
        @click="navigate(item.path)"
        class="flex flex-col items-center justify-center w-full h-full py-2 px-1 transition-all duration-200"
        :class="[
          isActive(item.path)
            ? 'text-emerald-400'
            : 'text-gray-500 hover:text-gray-300'
        ]"
      >
        <component
          :is="item.icon"
          class="w-6 h-6 mb-1 transition-transform duration-200"
          :class="{ 'scale-110': isActive(item.path) }"
        />
        <span class="text-xs font-medium">{{ item.label }}</span>
        <div
          v-if="isActive(item.path)"
          class="absolute bottom-1 w-1 h-1 rounded-full bg-emerald-400"
        />
      </button>
    </div>
  </nav>
</template>

// p3/petdaily/src/components/layout/BottomNav.tsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';

const BottomNav: React.FC = () => {
  const location = useLocation();

  const navItems = [
    { path: '/', icon: '🏠', label: '首页' },
    { path: '/square', icon: '🐾', label: '广场' },
    { path: '/profile', icon: '👤', label: '我的' },
  ];

  return (
    <nav className="fixed bottom-0 left-0 right-0 z-40 bg-white/95 backdrop-blur-md border-t border-pink-100">
      <div className="max-w-lg mx-auto">
        <div className="flex items-center justify-around h-16">
          {navItems.map((item) => {
            const isActive = location.pathname === item.path;
            return (
              <Link
                key={item.path}
                to={item.path}
                className={`flex flex-col items-center justify-center gap-1 px-4 py-2 transition-all ${
                  isActive
                    ? 'text-pink-500'
                    : 'text-gray-400 hover:text-gray-600'
                }`}
              >
                <span className={`text-xl ${isActive ? 'scale-110' : ''} transition-transform`}>
                  {item.icon}
                </span>
                <span className="text-xs font-medium">{item.label}</span>
              </Link>
            );
          })}
        </div>
      </div>
    </nav>
  );
};

export default BottomNav;
