// p1/shuati/src/components/layout/Navbar.tsx
import React from 'react'
import { Link, useLocation } from 'react-router-dom'
import { useStore } from '@/store/useStore'
import clsx from 'clsx'

export const Navbar: React.FC = () => {
  const location = useLocation()
  const theme = useStore(state => state.theme)
  const toggleTheme = useStore(state => state.toggleTheme)
  const user = useStore(state => state.user)

  const navLinks = [
    { path: '/', label: '题库', icon: '📚' },
    { path: '/profile', label: '个人中心', icon: '👤' },
  ]

  return (
    <nav className="sticky top-0 z-50 bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800 shadow-sm">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center gap-8">
            <Link to="/" className="flex items-center gap-2">
              <span className="text-2xl">💻</span>
              <span className="text-xl font-bold bg-gradient-to-r from-blue-500 to-purple-500 bg-clip-text text-transparent">
                DevOJ
              </span>
            </Link>

            <div className="hidden md:flex items-center gap-1">
              {navLinks.map((link) => (
                <Link
                  key={link.path}
                  to={link.path}
                  className={clsx(
                    'px-4 py-2 rounded-lg text-sm font-medium transition-colors',
                    location.pathname === link.path
                      ? 'bg-blue-50 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400'
                      : 'text-gray-600 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800'
                  )}
                >
                  <span className="mr-1">{link.icon}</span>
                  {link.label}
                </Link>
              ))}
            </div>
          </div>

          <div className="flex items-center gap-4">
            <button
              onClick={toggleTheme}
              className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
              aria-label="切换主题"
            >
              {theme === 'light' ? '🌙' : '☀️'}
            </button>

            {user && (
              <div className="flex items-center gap-3">
                <img
                  src={user.avatar}
                  alt={user.username}
                  className="w-8 h-8 rounded-full"
                />
                <span className="text-sm font-medium hidden sm:block">
                  {user.username}
                </span>
              </div>
            )}
          </div>
        </div>
      </div>
    </nav>
  )
}

// p3/foodshare/src/components/Navbar.vue
<template>
  <nav class="bg-white shadow-md sticky top-0 z-50">
    <div class="container mx-auto px-4">
      <div class="flex items-center justify-between h-16">
        <router-link to="/" class="flex items-center space-x-2">
          <span class="text-2xl">🍳</span>
          <span class="text-xl font-bold text-primary-600 font-serif">食记</span>
        </router-link>

        <div class="hidden md:flex items-center space-x-6">
          <router-link 
            to="/" 
            class="text-gray-700 hover:text-primary-500 transition-colors font-medium"
          >
            首页
          </router-link>
          <router-link 
            to="/create" 
            class="text-gray-700 hover:text-primary-500 transition-colors font-medium"
          >
            创建食谱
          </router-link>
        </div>

        <div class="flex items-center space-x-4">
          <router-link to="/shopping" class="relative p-2 text-gray-700 hover:text-primary-500 transition-colors">
            <ShoppingBag class="w-6 h-6" />
            <span 
              v-if="shoppingStore.pendingCount > 0"
              class="absolute -top-1 -right-1 bg-primary-500 text-white text-xs w-5 h-5 rounded-full flex items-center justify-center"
            >
              {{ shoppingStore.pendingCount }}
            </span>
          </router-link>
          <router-link to="/profile" class="p-2 text-gray-700 hover:text-primary-500 transition-colors">
            <User class="w-6 h-6" />
          </router-link>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ShoppingBag, User } from 'lucide-vue-next'
import { useShoppingStore } from '@/stores/shopping'

const shoppingStore = useShoppingStore()
</script>
